import { getToken } from "./utils";

export const config = {
    BASE_URL: "http://localhost:3001",
    AI_API_TOKEN: "sk-"
}

export const categories = ['Career', 'Fitness', 'Academic', 'Health', 'Chores', 'Self-Care'];

// export const aToken = "eyJraWQiOiJscVJ5b1RXMHR2RXdyUkpndmI1Y0hlMFpmNDM2Y0ZVUGQ1Y25ORDRmYk5nPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIwNmM0NWUxMS1lNTc2LTQwZjMtYjIzYS04YWEwYzk4YjU5MzYiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9CUWdPNWkyUkoiLCJjbGllbnRfaWQiOiI3MjJwdDBya25rZzBwMDBmbWwwN2pocWpqdSIsIm9yaWdpbl9qdGkiOiIwNTI2Y2M4Zi04NGFhLTRkNmMtYTRmZC1kZTFkZjQ5YmJlZTUiLCJldmVudF9pZCI6IjJiMWExNTZhLTZhZDMtNGZmOC04OWIxLTA2YTYwYjQzZTgyOCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE3MTUyMzA1MzIsImV4cCI6MTcxNTIzNDEzMiwiaWF0IjoxNzE1MjMwNTMyLCJqdGkiOiIxMGQxMmYzYy0yZTNjLTQ3MTItODY2MC0wNjFmMWM5NTViMGQiLCJ1c2VybmFtZSI6Imdyb3d3d3cifQ.2uZUUjRcMOrrO_NK28Be2qQCpra05RQhUsA38wTmiyxaon8C1NBtj-KBJVl4JLqtxGq3f2C4uf_ahLyBJnZrKA54MTf-x5_PKmgoOZqPMbwFmgwVZYYCoReYmTW5Dh4uRZxaahkiviBiefCpmuZh9A3EFmmmznPJhtX2Wsdnj3TXw9lauX4ZBaJfWz5kBJPretde23cz5TuXMJYXehpmv5ElvNKLH12GD_hMODRoSgQnzfap2OmZhAthacXxaVWzYlhJ-dTsah2voE_CcbTP_XoMHn-tRZ025sIZzxZ-16Umt5KSgGCwWH0jQZVwN6KAT2-xrCWeKHbIKWaJcdV2Gw";
export const aToken = getToken();
